Fix another null pointer, add examples to README.md
Fixes this specifically:
java.lang.NullPointerException: Cannot read the array length because "<local3>" is null